//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.19.0
//     from Assets/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/InputActions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @InputActions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""df70fa95-8a34-4494-b137-73ab6b9c7d37"",
            ""actions"": [
                {
                    ""name"": ""LeftPlayerMove"",
                    ""type"": ""Value"",
                    ""id"": ""15813dfa-3787-4218-92ea-ec79e4c0e83f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftPlayerAbilitySlot1"",
                    ""type"": ""Button"",
                    ""id"": ""5ce00bb7-2251-49d4-a70d-92d9054cbc9c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftPlayerAbilitySlot2"",
                    ""type"": ""Button"",
                    ""id"": ""0bc13d30-fe6b-4c69-b3e7-338a1dbb7b5f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftPlayerAbilitySlot3"",
                    ""type"": ""Button"",
                    ""id"": ""e16873cf-86ad-4ce9-b99d-420cf744d6bd"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftPlayerAbilitySlot4"",
                    ""type"": ""Button"",
                    ""id"": ""8631d3d7-82bd-4ad3-a33b-df3fba25cf68"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightPlayerMove"",
                    ""type"": ""Value"",
                    ""id"": ""f74e8e15-8999-4df6-b418-d0da01a6ee3e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightPlayerAbilitySlot1"",
                    ""type"": ""Button"",
                    ""id"": ""0c4808e5-b9cb-4a86-8596-20e65f29f37b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightPlayerAbilitySlot2"",
                    ""type"": ""Button"",
                    ""id"": ""3fc39dfc-1ed2-489f-9a7a-c6f3292fa0c4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightPlayerAbilitySlot3"",
                    ""type"": ""Button"",
                    ""id"": ""81723974-1902-427f-bf8f-8363b0886d60"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightPlayerAbilitySlot4"",
                    ""type"": ""Button"",
                    ""id"": ""fa76ee90-a464-4382-b9f4-c78f1798a7f5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""2d8d21f1-cb35-40e5-b32e-14852f9f044d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftPlayerMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""7bacb8ca-2d44-41a0-b357-be7c2b14ed97"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftPlayerMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""25556800-5f28-4c36-b4fb-3611c5dea8ee"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftPlayerMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4e8456fe-1f83-4e40-91a1-4c95bb0c0cfd"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftPlayerMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""21cf1a3b-3a4d-4dee-9ff9-d51cbe73a1c9"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftPlayerMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d1cf03e8-52f2-4e0f-a46a-84f31b4b064f"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftPlayerAbilitySlot1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0ad476d0-3ec0-4401-8528-c3bfe4158417"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftPlayerAbilitySlot2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd0bcb71-89ca-4fd7-85a0-bfd193bc102e"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftPlayerAbilitySlot3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""46157ee0-5de1-4136-84d5-5caad1460464"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftPlayerAbilitySlot4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""d0843077-c98a-43bb-a4ea-f0c4e4ace888"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightPlayerMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""8b758dbc-2a6b-4b14-8f15-81b886cc5326"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightPlayerMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""848d0859-49d8-4178-9bf5-7d1b648adf72"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightPlayerMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f353012c-8352-4da7-a962-3e35b44f4911"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightPlayerMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7a7ee7aa-0bba-4d5e-b1b9-048a08f14915"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightPlayerMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""728ce9c8-d3af-4e5f-9ad4-fb66ad2c2099"",
                    ""path"": ""<Keyboard>/numpad4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightPlayerAbilitySlot1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ad1a2df7-2d75-443f-b614-9ec6f3cd4f41"",
                    ""path"": ""<Keyboard>/numpad5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightPlayerAbilitySlot2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8d2f6d45-fd6f-466b-bd57-5e65c8774e32"",
                    ""path"": ""<Keyboard>/numpad6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightPlayerAbilitySlot3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f89df57-4de8-4651-a3e7-b2ee35559905"",
                    ""path"": ""<Keyboard>/numpad8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightPlayerAbilitySlot4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""RoundBreak"",
            ""id"": ""4fe67938-3798-4b79-b7ca-57a99f465085"",
            ""actions"": [
                {
                    ""name"": ""LeftPlayerAbilityMenu"",
                    ""type"": ""Button"",
                    ""id"": ""d08bc474-eab1-4be9-9b53-3aa2a3a5ecb0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightPlayerAbilityMenu"",
                    ""type"": ""Button"",
                    ""id"": ""93f00e86-ac4d-40f6-b0b2-e81987a8d8f5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ba97f913-9ec2-4f98-82d0-ac4252ec8f6e"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftPlayerAbilityMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6dcd3224-3413-4519-9e80-fd34e71de6e5"",
                    ""path"": ""<Keyboard>/numpad0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightPlayerAbilityMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Touch"",
            ""bindingGroup"": ""Touch"",
            ""devices"": [
                {
                    ""devicePath"": ""<Touchscreen>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Joystick"",
            ""bindingGroup"": ""Joystick"",
            ""devices"": [
                {
                    ""devicePath"": ""<Joystick>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""XR"",
            ""bindingGroup"": ""XR"",
            ""devices"": [
                {
                    ""devicePath"": ""<XRController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_LeftPlayerMove = m_Gameplay.FindAction("LeftPlayerMove", throwIfNotFound: true);
        m_Gameplay_LeftPlayerAbilitySlot1 = m_Gameplay.FindAction("LeftPlayerAbilitySlot1", throwIfNotFound: true);
        m_Gameplay_LeftPlayerAbilitySlot2 = m_Gameplay.FindAction("LeftPlayerAbilitySlot2", throwIfNotFound: true);
        m_Gameplay_LeftPlayerAbilitySlot3 = m_Gameplay.FindAction("LeftPlayerAbilitySlot3", throwIfNotFound: true);
        m_Gameplay_LeftPlayerAbilitySlot4 = m_Gameplay.FindAction("LeftPlayerAbilitySlot4", throwIfNotFound: true);
        m_Gameplay_RightPlayerMove = m_Gameplay.FindAction("RightPlayerMove", throwIfNotFound: true);
        m_Gameplay_RightPlayerAbilitySlot1 = m_Gameplay.FindAction("RightPlayerAbilitySlot1", throwIfNotFound: true);
        m_Gameplay_RightPlayerAbilitySlot2 = m_Gameplay.FindAction("RightPlayerAbilitySlot2", throwIfNotFound: true);
        m_Gameplay_RightPlayerAbilitySlot3 = m_Gameplay.FindAction("RightPlayerAbilitySlot3", throwIfNotFound: true);
        m_Gameplay_RightPlayerAbilitySlot4 = m_Gameplay.FindAction("RightPlayerAbilitySlot4", throwIfNotFound: true);
        // RoundBreak
        m_RoundBreak = asset.FindActionMap("RoundBreak", throwIfNotFound: true);
        m_RoundBreak_LeftPlayerAbilityMenu = m_RoundBreak.FindAction("LeftPlayerAbilityMenu", throwIfNotFound: true);
        m_RoundBreak_RightPlayerAbilityMenu = m_RoundBreak.FindAction("RightPlayerAbilityMenu", throwIfNotFound: true);
    }

    ~@InputActions()
    {
        UnityEngine.Debug.Assert(!m_Gameplay.enabled, "This will cause a leak and performance issues, InputActions.Gameplay.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_RoundBreak.enabled, "This will cause a leak and performance issues, InputActions.RoundBreak.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private List<IGameplayActions> m_GameplayActionsCallbackInterfaces = new List<IGameplayActions>();
    private readonly InputAction m_Gameplay_LeftPlayerMove;
    private readonly InputAction m_Gameplay_LeftPlayerAbilitySlot1;
    private readonly InputAction m_Gameplay_LeftPlayerAbilitySlot2;
    private readonly InputAction m_Gameplay_LeftPlayerAbilitySlot3;
    private readonly InputAction m_Gameplay_LeftPlayerAbilitySlot4;
    private readonly InputAction m_Gameplay_RightPlayerMove;
    private readonly InputAction m_Gameplay_RightPlayerAbilitySlot1;
    private readonly InputAction m_Gameplay_RightPlayerAbilitySlot2;
    private readonly InputAction m_Gameplay_RightPlayerAbilitySlot3;
    private readonly InputAction m_Gameplay_RightPlayerAbilitySlot4;
    /// <summary>
    /// Provides access to input actions defined in input action map "Gameplay".
    /// </summary>
    public struct GameplayActions
    {
        private @InputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public GameplayActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/LeftPlayerMove".
        /// </summary>
        public InputAction @LeftPlayerMove => m_Wrapper.m_Gameplay_LeftPlayerMove;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/LeftPlayerAbilitySlot1".
        /// </summary>
        public InputAction @LeftPlayerAbilitySlot1 => m_Wrapper.m_Gameplay_LeftPlayerAbilitySlot1;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/LeftPlayerAbilitySlot2".
        /// </summary>
        public InputAction @LeftPlayerAbilitySlot2 => m_Wrapper.m_Gameplay_LeftPlayerAbilitySlot2;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/LeftPlayerAbilitySlot3".
        /// </summary>
        public InputAction @LeftPlayerAbilitySlot3 => m_Wrapper.m_Gameplay_LeftPlayerAbilitySlot3;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/LeftPlayerAbilitySlot4".
        /// </summary>
        public InputAction @LeftPlayerAbilitySlot4 => m_Wrapper.m_Gameplay_LeftPlayerAbilitySlot4;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/RightPlayerMove".
        /// </summary>
        public InputAction @RightPlayerMove => m_Wrapper.m_Gameplay_RightPlayerMove;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/RightPlayerAbilitySlot1".
        /// </summary>
        public InputAction @RightPlayerAbilitySlot1 => m_Wrapper.m_Gameplay_RightPlayerAbilitySlot1;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/RightPlayerAbilitySlot2".
        /// </summary>
        public InputAction @RightPlayerAbilitySlot2 => m_Wrapper.m_Gameplay_RightPlayerAbilitySlot2;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/RightPlayerAbilitySlot3".
        /// </summary>
        public InputAction @RightPlayerAbilitySlot3 => m_Wrapper.m_Gameplay_RightPlayerAbilitySlot3;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/RightPlayerAbilitySlot4".
        /// </summary>
        public InputAction @RightPlayerAbilitySlot4 => m_Wrapper.m_Gameplay_RightPlayerAbilitySlot4;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="GameplayActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="GameplayActions" />
        public void AddCallbacks(IGameplayActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Add(instance);
            @LeftPlayerMove.started += instance.OnLeftPlayerMove;
            @LeftPlayerMove.performed += instance.OnLeftPlayerMove;
            @LeftPlayerMove.canceled += instance.OnLeftPlayerMove;
            @LeftPlayerAbilitySlot1.started += instance.OnLeftPlayerAbilitySlot1;
            @LeftPlayerAbilitySlot1.performed += instance.OnLeftPlayerAbilitySlot1;
            @LeftPlayerAbilitySlot1.canceled += instance.OnLeftPlayerAbilitySlot1;
            @LeftPlayerAbilitySlot2.started += instance.OnLeftPlayerAbilitySlot2;
            @LeftPlayerAbilitySlot2.performed += instance.OnLeftPlayerAbilitySlot2;
            @LeftPlayerAbilitySlot2.canceled += instance.OnLeftPlayerAbilitySlot2;
            @LeftPlayerAbilitySlot3.started += instance.OnLeftPlayerAbilitySlot3;
            @LeftPlayerAbilitySlot3.performed += instance.OnLeftPlayerAbilitySlot3;
            @LeftPlayerAbilitySlot3.canceled += instance.OnLeftPlayerAbilitySlot3;
            @LeftPlayerAbilitySlot4.started += instance.OnLeftPlayerAbilitySlot4;
            @LeftPlayerAbilitySlot4.performed += instance.OnLeftPlayerAbilitySlot4;
            @LeftPlayerAbilitySlot4.canceled += instance.OnLeftPlayerAbilitySlot4;
            @RightPlayerMove.started += instance.OnRightPlayerMove;
            @RightPlayerMove.performed += instance.OnRightPlayerMove;
            @RightPlayerMove.canceled += instance.OnRightPlayerMove;
            @RightPlayerAbilitySlot1.started += instance.OnRightPlayerAbilitySlot1;
            @RightPlayerAbilitySlot1.performed += instance.OnRightPlayerAbilitySlot1;
            @RightPlayerAbilitySlot1.canceled += instance.OnRightPlayerAbilitySlot1;
            @RightPlayerAbilitySlot2.started += instance.OnRightPlayerAbilitySlot2;
            @RightPlayerAbilitySlot2.performed += instance.OnRightPlayerAbilitySlot2;
            @RightPlayerAbilitySlot2.canceled += instance.OnRightPlayerAbilitySlot2;
            @RightPlayerAbilitySlot3.started += instance.OnRightPlayerAbilitySlot3;
            @RightPlayerAbilitySlot3.performed += instance.OnRightPlayerAbilitySlot3;
            @RightPlayerAbilitySlot3.canceled += instance.OnRightPlayerAbilitySlot3;
            @RightPlayerAbilitySlot4.started += instance.OnRightPlayerAbilitySlot4;
            @RightPlayerAbilitySlot4.performed += instance.OnRightPlayerAbilitySlot4;
            @RightPlayerAbilitySlot4.canceled += instance.OnRightPlayerAbilitySlot4;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="GameplayActions" />
        private void UnregisterCallbacks(IGameplayActions instance)
        {
            @LeftPlayerMove.started -= instance.OnLeftPlayerMove;
            @LeftPlayerMove.performed -= instance.OnLeftPlayerMove;
            @LeftPlayerMove.canceled -= instance.OnLeftPlayerMove;
            @LeftPlayerAbilitySlot1.started -= instance.OnLeftPlayerAbilitySlot1;
            @LeftPlayerAbilitySlot1.performed -= instance.OnLeftPlayerAbilitySlot1;
            @LeftPlayerAbilitySlot1.canceled -= instance.OnLeftPlayerAbilitySlot1;
            @LeftPlayerAbilitySlot2.started -= instance.OnLeftPlayerAbilitySlot2;
            @LeftPlayerAbilitySlot2.performed -= instance.OnLeftPlayerAbilitySlot2;
            @LeftPlayerAbilitySlot2.canceled -= instance.OnLeftPlayerAbilitySlot2;
            @LeftPlayerAbilitySlot3.started -= instance.OnLeftPlayerAbilitySlot3;
            @LeftPlayerAbilitySlot3.performed -= instance.OnLeftPlayerAbilitySlot3;
            @LeftPlayerAbilitySlot3.canceled -= instance.OnLeftPlayerAbilitySlot3;
            @LeftPlayerAbilitySlot4.started -= instance.OnLeftPlayerAbilitySlot4;
            @LeftPlayerAbilitySlot4.performed -= instance.OnLeftPlayerAbilitySlot4;
            @LeftPlayerAbilitySlot4.canceled -= instance.OnLeftPlayerAbilitySlot4;
            @RightPlayerMove.started -= instance.OnRightPlayerMove;
            @RightPlayerMove.performed -= instance.OnRightPlayerMove;
            @RightPlayerMove.canceled -= instance.OnRightPlayerMove;
            @RightPlayerAbilitySlot1.started -= instance.OnRightPlayerAbilitySlot1;
            @RightPlayerAbilitySlot1.performed -= instance.OnRightPlayerAbilitySlot1;
            @RightPlayerAbilitySlot1.canceled -= instance.OnRightPlayerAbilitySlot1;
            @RightPlayerAbilitySlot2.started -= instance.OnRightPlayerAbilitySlot2;
            @RightPlayerAbilitySlot2.performed -= instance.OnRightPlayerAbilitySlot2;
            @RightPlayerAbilitySlot2.canceled -= instance.OnRightPlayerAbilitySlot2;
            @RightPlayerAbilitySlot3.started -= instance.OnRightPlayerAbilitySlot3;
            @RightPlayerAbilitySlot3.performed -= instance.OnRightPlayerAbilitySlot3;
            @RightPlayerAbilitySlot3.canceled -= instance.OnRightPlayerAbilitySlot3;
            @RightPlayerAbilitySlot4.started -= instance.OnRightPlayerAbilitySlot4;
            @RightPlayerAbilitySlot4.performed -= instance.OnRightPlayerAbilitySlot4;
            @RightPlayerAbilitySlot4.canceled -= instance.OnRightPlayerAbilitySlot4;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="GameplayActions.UnregisterCallbacks(IGameplayActions)" />.
        /// </summary>
        /// <seealso cref="GameplayActions.UnregisterCallbacks(IGameplayActions)" />
        public void RemoveCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="GameplayActions.AddCallbacks(IGameplayActions)" />
        /// <seealso cref="GameplayActions.RemoveCallbacks(IGameplayActions)" />
        /// <seealso cref="GameplayActions.UnregisterCallbacks(IGameplayActions)" />
        public void SetCallbacks(IGameplayActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="GameplayActions" /> instance referencing this action map.
    /// </summary>
    public GameplayActions @Gameplay => new GameplayActions(this);

    // RoundBreak
    private readonly InputActionMap m_RoundBreak;
    private List<IRoundBreakActions> m_RoundBreakActionsCallbackInterfaces = new List<IRoundBreakActions>();
    private readonly InputAction m_RoundBreak_LeftPlayerAbilityMenu;
    private readonly InputAction m_RoundBreak_RightPlayerAbilityMenu;
    /// <summary>
    /// Provides access to input actions defined in input action map "RoundBreak".
    /// </summary>
    public struct RoundBreakActions
    {
        private @InputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public RoundBreakActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "RoundBreak/LeftPlayerAbilityMenu".
        /// </summary>
        public InputAction @LeftPlayerAbilityMenu => m_Wrapper.m_RoundBreak_LeftPlayerAbilityMenu;
        /// <summary>
        /// Provides access to the underlying input action "RoundBreak/RightPlayerAbilityMenu".
        /// </summary>
        public InputAction @RightPlayerAbilityMenu => m_Wrapper.m_RoundBreak_RightPlayerAbilityMenu;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_RoundBreak; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="RoundBreakActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(RoundBreakActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="RoundBreakActions" />
        public void AddCallbacks(IRoundBreakActions instance)
        {
            if (instance == null || m_Wrapper.m_RoundBreakActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_RoundBreakActionsCallbackInterfaces.Add(instance);
            @LeftPlayerAbilityMenu.started += instance.OnLeftPlayerAbilityMenu;
            @LeftPlayerAbilityMenu.performed += instance.OnLeftPlayerAbilityMenu;
            @LeftPlayerAbilityMenu.canceled += instance.OnLeftPlayerAbilityMenu;
            @RightPlayerAbilityMenu.started += instance.OnRightPlayerAbilityMenu;
            @RightPlayerAbilityMenu.performed += instance.OnRightPlayerAbilityMenu;
            @RightPlayerAbilityMenu.canceled += instance.OnRightPlayerAbilityMenu;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="RoundBreakActions" />
        private void UnregisterCallbacks(IRoundBreakActions instance)
        {
            @LeftPlayerAbilityMenu.started -= instance.OnLeftPlayerAbilityMenu;
            @LeftPlayerAbilityMenu.performed -= instance.OnLeftPlayerAbilityMenu;
            @LeftPlayerAbilityMenu.canceled -= instance.OnLeftPlayerAbilityMenu;
            @RightPlayerAbilityMenu.started -= instance.OnRightPlayerAbilityMenu;
            @RightPlayerAbilityMenu.performed -= instance.OnRightPlayerAbilityMenu;
            @RightPlayerAbilityMenu.canceled -= instance.OnRightPlayerAbilityMenu;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="RoundBreakActions.UnregisterCallbacks(IRoundBreakActions)" />.
        /// </summary>
        /// <seealso cref="RoundBreakActions.UnregisterCallbacks(IRoundBreakActions)" />
        public void RemoveCallbacks(IRoundBreakActions instance)
        {
            if (m_Wrapper.m_RoundBreakActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="RoundBreakActions.AddCallbacks(IRoundBreakActions)" />
        /// <seealso cref="RoundBreakActions.RemoveCallbacks(IRoundBreakActions)" />
        /// <seealso cref="RoundBreakActions.UnregisterCallbacks(IRoundBreakActions)" />
        public void SetCallbacks(IRoundBreakActions instance)
        {
            foreach (var item in m_Wrapper.m_RoundBreakActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_RoundBreakActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="RoundBreakActions" /> instance referencing this action map.
    /// </summary>
    public RoundBreakActions @RoundBreak => new RoundBreakActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    private int m_TouchSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme TouchScheme
    {
        get
        {
            if (m_TouchSchemeIndex == -1) m_TouchSchemeIndex = asset.FindControlSchemeIndex("Touch");
            return asset.controlSchemes[m_TouchSchemeIndex];
        }
    }
    private int m_JoystickSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme JoystickScheme
    {
        get
        {
            if (m_JoystickSchemeIndex == -1) m_JoystickSchemeIndex = asset.FindControlSchemeIndex("Joystick");
            return asset.controlSchemes[m_JoystickSchemeIndex];
        }
    }
    private int m_XRSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme XRScheme
    {
        get
        {
            if (m_XRSchemeIndex == -1) m_XRSchemeIndex = asset.FindControlSchemeIndex("XR");
            return asset.controlSchemes[m_XRSchemeIndex];
        }
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Gameplay" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="GameplayActions.AddCallbacks(IGameplayActions)" />
    /// <seealso cref="GameplayActions.RemoveCallbacks(IGameplayActions)" />
    public interface IGameplayActions
    {
        /// <summary>
        /// Method invoked when associated input action "LeftPlayerMove" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftPlayerMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LeftPlayerAbilitySlot1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftPlayerAbilitySlot1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LeftPlayerAbilitySlot2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftPlayerAbilitySlot2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LeftPlayerAbilitySlot3" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftPlayerAbilitySlot3(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LeftPlayerAbilitySlot4" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftPlayerAbilitySlot4(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RightPlayerMove" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightPlayerMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RightPlayerAbilitySlot1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightPlayerAbilitySlot1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RightPlayerAbilitySlot2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightPlayerAbilitySlot2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RightPlayerAbilitySlot3" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightPlayerAbilitySlot3(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RightPlayerAbilitySlot4" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightPlayerAbilitySlot4(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "RoundBreak" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="RoundBreakActions.AddCallbacks(IRoundBreakActions)" />
    /// <seealso cref="RoundBreakActions.RemoveCallbacks(IRoundBreakActions)" />
    public interface IRoundBreakActions
    {
        /// <summary>
        /// Method invoked when associated input action "LeftPlayerAbilityMenu" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftPlayerAbilityMenu(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RightPlayerAbilityMenu" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightPlayerAbilityMenu(InputAction.CallbackContext context);
    }
}
